current_file_input: output_2024-06-22.txt
current_file_processor: output_2024-06-22.txt
header_processor: header_baumer_hivac2_v1
input_dir: input_dir
path_log: logs
pointer_file: 0
processed_dir: ciclos
serial_port: /dev/ttyS0
